SELECT
  pcprodut.CODPROD,
  Upper(pcprodut.DESCRICAO),
  PCTABPR.PTABELA,
  pcprodut.DIRFOTOPROD,
  :DIGITE_SEU_NOME,
  replace(:DESCRICAO,'%','')
FROM
  pcprodut,
  PCTABPR
WHERE
  PCTABPR.CODPROD = pcprodut.CODPROD
  AND pcprodut.DESCRICAO LIKE :DESCRICAO
  AND pcprodut.CODPROD LIKE :CODIGO_PRODUTO
  AND PCTABPR.NUMREGIAO = 1
  AND PCTABPR.PTABELA IS NOT NULL

